server:
  port: 8888

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URI}
          predicates:
            - Path=/authservice/v1/**
          filters:
            - StripPrefix=2
        - id: user-service
          uri: ${USER_SERVICE_URI}
          predicates:
            - Path=/userservice/v1/**
          filters:
            - JwtAuthentication
            - StripPrefix=2

